server:
  port: 8081

spring:
  application:
    name: msc-provider

eureka:
  instance:
    hostname: localhost
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      # 指定要连接的Eureka服务中心
      # defaultZone: http://localhost:8000/eureka
      defaultZone: http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka,http://eureka8300.com:8300/eureka

logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    com.abc: debug

# Eureka工作界面中instance-id处链接的信息
info:
  company.name: www.abc.com
  company.addr: China Beijing
  company.tel: 12345678
  app.name: abc-msc
  app.desc: mic-server-cloud
  author: abc

management:
  endpoint:
    # 启用shutdown
    shutdown:
      enabled: true
#    pause:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: service-registry


