server:
  port: 8200

eureka:
  instance:
    hostname: eureka8200.com
  client:
    register-with-eureka: false # 指定是否需要注册到Eureka注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka,http://eureka8300.com:8300/eureka
  server:
    renewal-percent-threshold: 0.85
#    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
#    #由于启用了evict其实就用不太上改这个配置了
#    #默认180s
     #response-cache-update-interval-ms: 3000
#    #启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 3000
#    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
#    #由于启用了evict其实就用不太上改这个配置了
#    #默认180s
#    response-cache-auto-expiration-in-seconds: 180