server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 指定是否需要注册到Eureka注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka
